---
title: '**STOR 320.2: Intro to Data Science**'
geometry: margin=2
output:
  prettydoc::html_pretty:
    theme: cayman
  html_document:
    toc: yes
    df_print: paged
  pdf_document:
    toc: yes
---

<style type="text/css">

div {
color: #13294B;
}

#TOC {
  color: #4B9CD3;
}

.list-group-item.active, .list-group-item.active:focus, .list-group-item.active:hover {
  color: #4B9CD3;
  background-color: #13294B;
}

a:link {
    color: #4B9CD3;
    text-decoration: none;
}

a:visited {
        text-decoration: none;
color: #4B9CD3;

}
a:hover {
color: #4B9CD3;
background-color: #13294B;
}

.main-container {
  max-width: 300px;
  margin-left: auto;
  margin-right: auto;
}

.column {
  float: left;
  width: 50%;
}

.row:after {
  content: "";
  display: table;
  clear: both;
} 

</style>

# **About the Course**

See the **[syllabus](Syllabi/320_Syllabus.pdf)** for details. The course is divided into three rough parts,

1. Core data science coding skills
2. Modeling
3. Advanced topics

- Instructor: **[Yao Li](https://liyao880.github.io/yaoli/)**

- Instructional Assistants: 
    - **[Taylor M Petty](http://stat-or.unc.edu/people/graduate-students-department)**
    - **[Pavlos Zoubouglou](http://stat-or.unc.edu/people/graduate-students-department)**
    - **[Sam Booth](http://stat-or.unc.edu/people/graduate-students-department)**

- Lab Sections: 
    - 320.404 by Pavlos: T 9:30AM-10:20AM
    - 320.405 by Taylor: T 5:00PM-5:50PM
    - 320.406 by Sam: Th 9:30AM-10:20AM


- Zoom Links:
    - **[Lectures:](https://unc.zoom.us/j/93501182856?pwd=b3ZoZlZTdndrYW95MGswTEpGSU1qdz09)** MWF 8:00AM-8:50AM
    - **[320.404 by Pavlos](https://unc.zoom.us/j/96678226561)**: T 9:30AM-10:20AM
    - **[320.405 by Taylor](https://unc.zoom.us/j/91440986085?pwd=WUpKeW5hVG0rNGRXaXlZZStJL2xuUT09)**: T 5:00PM-5:50PM
    - **[320.406 by Sam](https://unc.zoom.us/j/5891075192)**: Th 9:30AM-10:20AM
    - **[Instructor Office Hours:](https://unc.zoom.us/j/99751369535)** WF 9:00AM-10:00AM
    - **[Taylor Office Hours:](https://unc.zoom.us/j/91440986085?pwd=WUpKeW5hVG0rNGRXaXlZZStJL2xuUT09)** M 2:30PM-3:30PM, W 1:30PM-2:30PM
    - **[Pavlos Office Hours:](https://unc.zoom.us/j/2903979720)** M 10:00AM-11:00AM, F 1:00PM-2:00PM
    - **[Sam Office Hours:](https://unc.zoom.us/j/5891075192)** TTh 4:00PM-5:00PM


# **Course Material**

| Date | Lecture | Slides | Tutorial|
|------|---------|--------:|--------:|
|Jan. 20| [Welcome](https://uncch.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=a47a655b-4f19-4053-8b1f-acb600e76603) |[Slides](Lecture/Lecture01/Lecture 01 Welcome.pdf) | |
|Jan. 22| [Data Visualization](https://uncch.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=07f214c4-0df4-459c-ae76-acb800ed8061)| [Slides](Lecture/Lecture02/Lecture 02 Data_Visualization_Lecture.pdf) | [Tutorial01](Tutorial/Tutorial01.html)([.rmd](https://drive.google.com/file/d/1axwnhheH0IMH3xkE_GJWSREK7gdzMLvd/view?usp=sharing))|
|Jan. 25| [RMarkdown I](https://uncch.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=3e6fea7d-a17e-4f2c-83c5-acbb00e97185) |[Slides](Lecture/Lecture03/Lecture 03 Workflow_Lecture.pdf)| |
|Jan. 27| [RMarkdown II](https://uncch.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=0e2c6115-9347-46c0-a15f-acbd00ead6c6) ||[Tutorial02](Tutorial/Tutorial02-sol.html)([.zip](https://drive.google.com/file/d/1DpCkW9N_BdJU0zc1W2J5rMK-MByrTQFZ/view?usp=sharing))|
|Jan. 29| [Data Transformation I](https://uncch.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=56533c15-32f6-49d3-ba99-acbf00e95196) |[Slides](Lecture/Lecture05/Lecture 05 Data_Transformation.pdf)|[Lecture05.rmd](https://drive.google.com/file/d/1QJLG8MQj2ncr4wGkiZL0CHlX2x9wZemo/view?usp=sharing)|
|Feb. 1| [Data Transformation II](https://uncch.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=78f334ee-2e31-45bc-a03d-acc200e77db8) ||[Tutorial03](Tutorial/Tutorial03_sol.html)([.rmd](https://drive.google.com/file/d/1zPZpvvshqarahO7qJNqTiX3SCXk-azK5/view?usp=sharing))|
|Feb. 3| [Data Transformation III](https://uncch.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=ffdb6c72-8e96-4fa9-a391-acc400ee0c79)|[Slides](Lecture/Lecture07/Lecture 07 Data_Transformation.pdf)||
|Feb. 5| [Data Transformation IV](https://uncch.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=b3b327d3-7e82-4ed9-884d-acc600f0c63f) ||[Tutorial04](Tutorial/Tutorial04.html)([.zip](https://drive.google.com/file/d/1UEt-RVM4qAI889eXr_xphXL1M3wbQeqS/view?usp=sharing))|
|Feb. 8| [Final Project Instruction](https://uncch.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=19e851c3-2fd6-451f-86af-acc900e8b49d) |[Slides](Lecture/Lecture09/Lecture 09 Final_Project.pdf)||
|Feb. 10| [Data Import](https://uncch.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=35a9948d-9b68-4e56-82d9-accb00e8283d) |[Slides](Lecture/Lecture10/Lecture 10 Data_Import.pdf)||
|Feb. 12| [Exploratory Data Analysis I](https://uncch.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=6529623f-d95c-4142-bab3-accd00e90377) |[Slides](Lecture/Lecture11/Lecture 11 Exploratory_Data_Analysis.pdf)||
|Feb. 15| Wellness Day |||
|Feb. 17| Project Proposal Discussion |||
|Feb. 19| Project Proposal Discussion |||
|Feb. 22| [Exploratory Data Analysis II](https://uncch.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=1a482bc2-7636-4e9d-81aa-acd700e90539) |[Slides](Lecture/Lecture12/Lecture 12 Exploratory_Data_Analysis.pdf)|[Tutorial05](Tutorial/Tutorial-05_sol.html)([.rmd](https://drive.google.com/file/d/11MStXK9znEnu-MMmj1ZPMqSMIyciytNN/view?usp=sharing))|
|Feb. 24| [Tidy Data I](https://uncch.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=0d214076-b2ec-4da1-9d10-acd900e40078) |[Slides](Lecture/Lecture13/Lecture13 Tidy Data.pdf)||
|Feb. 26| [Tidy Data II](https://uncch.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=3a4d613e-8688-4e04-8991-acdb00e8e99d) ||[Tutorial06](Tutorial/Tutorial06_sol.html)([.rmd](https://drive.google.com/file/d/1ONpR1uWseqxfUJR4UgkqHMlMvV8u5Gdb/view?usp=sharing))|
|Mar. 1| [Web Scraping I](https://uncch.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=82b7e0c7-ffe3-4227-951d-acde00ef2238) |[Slides](Lecture/Lecture15/Lecture 15 Web Scraping.pdf)|[Tutorial07](Tutorial/Tutorial07.html)([.rmd](https://drive.google.com/file/d/1GaRdMRkDsI3rnY4tWh5RR4wdo423FRhd/view?usp=sharing))|
|Mar. 3| [Web Scraping II](https://uncch.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=b3a73808-0226-4ec0-b49b-ace000e95880) |[Slides](Lecture/Lecture16/Lecture 16 Web Scraping II.pdf)|[Tutorial08](Tutorial/Tutorial08_sol.html)([.zip](https://drive.google.com/file/d/1Hnj10zSpNxLnH_3B2hpNVSG0znimHY4R/view?usp=sharing))|
|Mar. 5| [Joins I](https://uncch.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=809f5b59-f1fd-4ad0-a2c8-ace200e5e9bf) |[Slides](Lecture/Lecture17/Lecture 17 Joins.pdf)|[Lecture17](Tutorial/Lecture17.html)([.rmd](https://drive.google.com/file/d/1CsQXu0QzF6N9n64aeGVVsKqNGlG3ODj_/view?usp=sharing))|
|Mar. 8| [Joins II](https://uncch.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=b34a3653-9791-4f9f-b121-ace500eeba1e) ||[Analysis 2](Homework/Analysis 2/Analysis_2.html)([.zip](https://drive.google.com/file/d/1lop1deCM_s5r7aaPqoa1uQtZdC3SyMBi/view?usp=sharing))|
|Mar. 10| [Factors](https://uncch.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=dbe15939-0086-4079-8b3c-ace700e6c583) |[Slides](Lecture/Lecture19/Lecture 19 Factors.pdf)||
|Mar. 12| Wellness Day |||
|Mar. 15|[Programming I](https://uncch.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=ee0319dc-d480-44e4-a2e5-acec00d9dd3f) |[Slides](Lecture/Lecture20/Lecture 20 Programming I.pdf)|[Tutorial09](Tutorial/Tutorial09.html)([.rmd](https://drive.google.com/file/d/1_Rx0ZCsIcn43Lxxed2wcdDv14L58GlTQ/view?usp=sharing))|
|Mar. 17| [Programming II](https://uncch.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=48d3ea94-c441-4a6c-9150-acee00da9ba7) |[Slides](Lecture/Lecture21/Lecture 21 Programming II.pdf)|[Tutorial10](Tutorial/Tutorial10.html)([.rmd](https://drive.google.com/file/d/10VDpMfk13nKV5h40TBWR0r3Af2qqOb5N/view?usp=sharing))|
|Mar. 19| [Programming III](https://uncch.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=5649b42e-3b55-4c04-bae5-acf000d75b94) |[Slides](Lecture/Lecture22/Lecture 22 Programming III.pdf)||
|Mar. 22| [Programming IV](https://uncch.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=fb7941db-e139-4fc6-8edf-acf300d939a4) |[Slides](Lecture/Lecture23/Lecture 23 Programming IV.pdf)|[Analysis 3](Homework/Analysis 3/Analysis-3.html)([.zip](Homework/Analysis 3/Analysis 3.zip))|
|Mar. 24| Group Work Day |||
|Mar. 26| [Modeling I](https://uncch.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=bddc3672-f903-4197-ae69-acf700d8b90e) |[Slides](Lecture/Lecture24/Lecture 24 Modeling I.pdf)||
|Mar. 29| [Modeling II](https://uncch.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=ef3c84c4-ad8f-469d-8147-acfa00d9be20) |[Slides](Lecture/Lecture25/Lecture 25 Modeling II.pdf)|[Tutorial11](Tutorial/Tutorial11.html)([.zip](https://drive.google.com/file/d/1W6jpeb-A0LTcqwP5BaNrR4va7JZMiKDu/view?usp=sharing))|
|Mar. 31| Modeling III |||
|Apr. 2| Holiday |||
|Apr. 5| Wellness Day |||
|Apr. 7| Modeling IV |||
|Apr. 9| Modeling V |||
|Apr. 12| Modeling VI |||
|Apr. 14| Modeling VII |||
|Apr. 16| Modeling VIII |||
|Apr. 19| Modeling IX |||
|Apr. 21| Modeling X |||
|Apr. 23| R Shiny I |||
|Apr. 26| R Shiny II |||
|Apr. 28| Data Ethics |||
|Apr. 30| Final Presentation  |||
|May. 3| Final Presentation |||
|May. 5| Final Presentation |||

# **Homework Tracker**

All homework assignments are to be submitted via **[Gradescope](https://www.gradescope.com/)**. 

| Date assigned | Instructions | Solutions| Due Date (Time) |
|----------|:--------:|:-------------:|----------------:|
| Jan 22  | [HW1](Homework/HW-1.html)([.Rmd](Homework/HW 1.rmd)) | [SOL1](Solutions/HW1_Solution.html) |Jan 29 (11:55 PM) |
| Feb 1  | [HW2](Homework/HW-2.html)([.Rmd](Homework/HW 2.rmd)) | [SOL2](Solutions/HW2_Solution.html) |Feb 8 (11:55 PM) |
| Feb 8  | [A1](Homework/Analysis 1/Analysis-1.html)([.zip](Homework/Analysis 1/Analysis 1.zip)) | [A1](Solutions/Analysis-1_Sol.html) |Feb 22 (11:55 PM) |
| Feb 22  | [HW3](Homework/HW-3.html)([.Rmd](Homework/HW 3.rmd)) | [SOL3](Solutions/HW3_Solution.html) |Feb 28 (11:55 PM) |
| Feb 28  | [HW4](Homework/HW-4.html)([.Rmd](Homework/HW 4.rmd)) | |Mar 7 (11:55 PM) |
| Mar 7  | [A2](Homework/Analysis 2/Analysis_2.html)([.zip](https://drive.google.com/file/d/1lop1deCM_s5r7aaPqoa1uQtZdC3SyMBi/view?usp=sharing)) | |Mar 14 (11:55 PM) |
| Mar 14  | [HW5](Homework/HW-5.html)([.Rmd](Homework/HW 5.rmd)) | |Mar 21 (11:55 PM) |
| Mar 21  | [A3](Homework/Analysis 3/Analysis-3.html)([.zip](Homework/Analysis 3/Analysis 3.zip)) | |Apr 4 (11:55 PM) |
| Apr 4  | [HW6](Homework/HW-6.html)([.Rmd](Homework/HW 6.rmd)) | |Apr 11 (11:55 PM) |
| Apr 11  | [HW7](Homework/HW-7.html)([.Rmd](Homework/HW 7.rmd)) | |Apr 18 (11:55 PM) |
| Apr 18  | [A4](Homework/Analysis 4/Analysis-4.html)([.zip](Homework/Analysis 4/Analysis 4.zip)) | |May 2 (11:55 PM) |
|          |        |     |           |

# **Final Project Details**

For the final project, each section of STOR 320 will be divided (ideally) into research groups of size 5. To ensure fairness, students will be assigned randomly based on the `sample` function in **R**. 

## Research Group Assignments

To find your research group, see the **[spreadsheet](https://docs.google.com/spreadsheets/d/10gwXH2bWP3iTnW9p6air6PypyP1JkartuFJmSkvais0/edit?usp=sharing)** sponsored by Google.

## Four Roles

Although everyone is responsible for the entire project, each member of the group will be assigned a specific role for accountability and consistency. These four specific roles are described as follows:

- **The Creator:** Meet with Instructor to Propose Your Group's Research Idea, Lead Designer in Slides

- **The Interpreter:** Schedule and Meet with Instructor or Instructional Assistant to Share Findings from Exploratory Analysis, Evaluate Practice Presentation

- **The Orator(s):** Give a Captivating 5-7 Minute Slideshow Presentation During the Last Three Lectures

- **The Deliverer:** Deliver Your Group from Evil by Editing and Submitting the Exploratory Analysis and Final Report via Gradescope Before the Deadline

## Four Parts Including Point Values

This final project will be divided into four parts worth a total of 100 points. Each part will have a clear rubric as non-subjective as possible. The parts along with total point values are found below:

* **[P1: Project Proposal](Final Project/Project-Proposal.html)** *(10 Points)*
    + [Template](Final Project/Project_Proposal_Template.html)([.Rmd](Final Project/Project_Proposal_Template.Rmd))
    + [Data World](https://data.world/datasets/download)
    + [US Government Data](https://www.data.gov/)
    + [Kaggle](https://www.kaggle.com/)
    + [Free Data Info I](https://www.forbes.com/sites/bernardmarr/2016/02/12/big-data-35-brilliant-and-free-data-sources-for-2016/#63f06f60b54d)
    + [Free Data Info II](https://r-dir.com/reference/datasets.html)


* **[P2: Exploratory Data Analysis](Final Project/Exploratory-Data-Analysis.html)** *(20 Points)*
    + [Template](Final Project/EDA_Template.html) ([.Rmd](Final Project/EDA_Template.rmd))
    
* **[P3: Final Written Paper](Final Project/Final-Paper.html)** *(40 Points)*
    + [Template](Final Project/Final_Report_Template.html)([.Rmd](Final Project/Final_Report_Template.rmd))
    + [Group Scoring](https://forms.gle/8ALCe4H1HR8JCTb37)
    
* **[P4: Final Presentation](Final Project/Final-Presentation.html)** *(30 Points)*

    
## Due Dates of Individual Parts

| Part | Description |Method of Submission| Due Date (Time) |
|------|-------------|-------------------|----------------:|
| P1  | Project Proposal | Gradescope | Feb16 (11:55PM)|
|   | Proposal Meeting | Class | Feb 17 / Feb 19 (8:00AM-9:15AM)|
| P2  | Exploratory Data Analysis | Gradescope | Mar 26 (11:55PM)|
|   | EDA Meeting | Lab | Week of Mar 29 to April 4 |
| P3  | Final Report|Gradescope|May 5 (11:55PM)|
| P4  | Presentation Slides |Gradescope| Apr 29 (11:55PM)|
|   | Final Presentation|Class| Apr 30 / May 3 / May 5 (8:00AM-8:50AM)|
||||

## Above Average Final Projects from Previous Courses

- **[Pokemon](Final Project/SP2019_EX1.html)**
- **[Seattle Housing](Final Project/SP2019_EX2.html)**
- **[Missing Migrants](Final Project/SU2019_EX1.html)**
- **[Youtube](Final Project/FA2019_EX1.html)**
- **[CDC](Final Project/FA2019_EX2.html)**

# **Acknowledgements**

Thanks to Dr. Mario and Dr. Characiejus for sharing their course materials. 

# **Reading**

- **[R for Data Science](https://r4ds.had.co.nz/)** (R4DS)

- **[R Programming for Data Science](https://drive.google.com/file/d/1XVF5v4MTBhIp_dq9MzTI0TtPfVrF6eaZ/view?usp=sharing)** (RP4DS)

- **[Text Mining with R](https://www.tidytextmining.com/)** (TMwR)

- **[The Art of R Programming](https://drive.google.com/file/d/1gR7Yr9-pIZ-f315bZCXfDj9yPWaZDflD/view?usp=sharing)** (AoRP)

- **[A First Course in Statistical Programming with R](https://drive.google.com/file/d/1NBadpF5MLWI3AFsyWo3nbpQnL8sWeZdT/view?usp=sharing)** (FCSPR)

- **[ModernDive](https://moderndive.com/index.html)** (MD)

- **[An Introduction to Statistical Learning](https://drive.google.com/file/d/1jKxVWG89KvWr_-70sOeEeLK4CUB09sRu/view?usp=sharing)** (ISLR)


# **Additional resources**

- **[Installing R](https://cran.r-project.org/)**

- **[Installing R Studio](https://www.rstudio.com/products/rstudio/#Desktop)**

- **[Additional Necessary Tools for Mac Users](https://mac.r-project.org/tools/)**

- **[Instructions for Accessing R Studio on the UNC Server](https://drive.google.com/file/d/1ATZO-wpuqzHbXVnJqm7wXpt-yfMbo2Jy/view?usp=sharing)**

- **[Rmarkdown Cheat Sheet](https://www.rstudio.com/wp-content/uploads/2016/03/rmarkdown-cheatsheet-2.0.pdf)**

- **[ggplot2 Cheat Sheet](https://www.rstudio.com/wp-content/uploads/2015/03/ggplot2-cheatsheet.pdf)**

- **[Color Options](https://paulvanderlaken.files.wordpress.com/2017/08/ggplot2-color-colours-names-cheatsheet.png?w=559&amp;h=1024)**

- **[Data Wrangling Cheat Sheet](https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf)**

- **[R Shiny Cheat Sheet](https://shiny.rstudio.com/images/shiny-cheatsheet.pdf)**

- **[R Strings Cheat Sheet](https://evoldyn.gitlab.io/evomics-2018/ref-sheets/R_strings.pdf)**

This page was last updated on `r Sys.time()` Eastern Time.
