---
title: '**Final Presentation**'
geometry: margin=2
output:
  html_document:
    theme: cosmo
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
---

<style type="text/css">
.main-container {
  max-width: 300px;
  margin-left: auto;
  margin-right: auto;
}
</style>

# **Purpose**

The purpose of the final presentation is to verbally communicate your group's process to answer a question using data. A slideshow with appropriate visuals and text should be utilized. This is your group's opportunity to enthusiastically share your findings with your classmates. **The findings should not overlap with what you have done in the EDA report.**

# **Requirements**

In 7 minutes, you will focus your presentation on a single question. Ideally, this should be 1 of the 2 questions you will write about in your final paper. A slideshow should be used to organize the information. First, you should creatively introduce the question and orally defend why your group found this particular question interesting. Next, you should briefly discuss the data your group used to answer this question. Figures and tables can be used to highlight variables of interest. Last, you should explain the statistical methods you employed to answer the question and the results you discovered. I recommend using multiple modeling techniques.

During the presentation, I will evaluate the clarity of the question, the explanation of the methods, techinical accuray, and the organization of the content. Additionally, I will assess the presentation skills and the quality of the slides. Slides should not be cluttered, too wordy, unreadable, or plain. The Orator should not read directly from the slides. This is a short presentation that should be well-rehearsed.

The Orator is solely responsible for giving the presentation. All members should help develop the slides, organize the information, and provide an audience for the Orator to practice. Everyone should proofread the slides since grammatical and spelling errors will result in a loss of points. After 7 minutes, I will abruptly cut off your presentation. During the Q&A session, both the instructor and students may ask questions, and the ability to address these questions effectively will also be evaluated.

The final presentations will take place during the last three lectures. Time slots will be prioritized according to email and posted on a google spreadsheet linked on the website. I highly recommend scheduling your meeting as soon as possible to ensure you have a preferred spot. The Deliverer is responsible for submitting the slides in PDF format to Canvas. The slides are due **before presentation day**. For example, if the group is scheduled to present on Nov 26, the slides should be submitted by Nov 25 (11:55PM). If the Deliverer fails to submit the slides before the deadline, your group will not receive a grade for the presentation. This penalty will affect the entire group. Attendance of all members is required. Each member that fails to attend will automatically lose five points from their individual grade. 


# **Rubric**

|Requirement|Points|
|-------|------:|
|Organization and Structure|5 Points|
|Presentation Skills|5 Points|
|Quality of Slides|5 Points|
|Technical Accuracy|10 Points|
|Finish Within the Scheduled Time|2 Points|
|Q&A|3 Points|
|**Total**|**30 Points**|
|||
