---
title: "Lecture04"
author: "Yao Li"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(nycflights13)
# Code for installing the package: install.packages("nycflights13")
```

## NYC Flights Data

```{r, eval=F}
View(flights)
```

```{r, eval=F}
?flights
```

```{r, eval=F}
flights
```

## Basics of dplyr

```{r, eval=F}
filter(flights, month==9)
```

## Comparisons
```{r}
x=3
y=4
```

```{r}
x<y
x>y
x!=y
x==y
```

```{r}
x=1/49
y=49
x*y==1
near(x*y,1)
```

## Logical Operators
```{r}
x = TRUE
y = FALSE
x&y
x|y
!x
!x|!y
!(x&y)
!x&!y
```

## Missing Values
```{r}
NA>5
10==NA
NA+10
NA/2
```

```{r}
male.age=c(NA,20,21,35,22,NA)
female.age=c(21,NA,23,33,22,NA)
age.data=tibble(ma=male.age,fa=female.age)
age.data
```

```{r}
is.na(male.age)
na.omit(age.data)
mean(male.age)
mean(male.age,na.rm=T)
```

## filter()
```{r, eval=F}
filter(flights, month==9,day==13,origin ==“LGA”)
```

```{r, eval=F}
filter(flights, month==11|month==12)
```

```{r, eval=F}
filter(flights, month %in% c(11,12))
```

```{r, eval=F}
filter(flights, !(arr_delay>120 | dep_delay>120) )
```

```{r, eval=F}
filter(flights, arr_delay <= 120, dep_delay <= 120)
```

```{r, eval=F}
filter(flights, dep_delay==0, arr_delay==0)
```

```{r, eval=F}
filter(flights, dep_delay==0 & arr_delay==0)
```

```{r, eval=F}
filter(flights, is.na(air_time) )
```

```{r, eval=F}
filter(flights, !is.na(air_time) )
```

```{r, eval=F}
na.omit(flights)
```

## arrange()
```{r, eval=F}
arrange(fligts,year,month,day)
```

```{r, eval=F}
arrange(fligts,day, dep_time)
```

```{r, eval=F}
arrange(fligts,desc(day), dep_time)
```

```{r}
miss.data=tibble(x=c(1,1,NA,3,3,NA),
                 y=c(NA,4,NA,5,NA,7))
miss.data
```

```{r}
arrange(miss.data, x)
```

```{r}
arrange(miss.data, desc(x))
```

## select()

```{r}
names(flights)
```

```{r, eval=F}
data1=select(flights,year,month,day)
names(data1)
```

```{r, eval=F}
data2=select(flights,dep_time:arr_delay)
names(data2)
```

```{r, eval=F}
data3=select(flights,-(dep_time:arr_delay))
names(data3)
```

```{r, eval=F}
length(names(flights))
data4=select(flights,c(1,3,8,12))
names(data4)
```

```{r, eval=F}
data5=select(flights,-c(1,3,8,12))
names(data5)
```

```{r, eval=F}
data6=select(flights,starts_with("dep"))
names(data6)
```

```{r, eval=F}
data7=select(flights,ends_with("delay"))
names(data7)
```

```{r, eval=F}
data8=select(flights,contains("ar"))
names(data8)
```

```{r, eval=F}
data9=select(flights,yr=year)
names(data9)
```


```{r, eval=F}
data10=rename(flights,yr=year)
names(data10)
```

```{r, eval=F}
head(flights)
```

```{r, eval=F}
data11=select(flights,dep_time,arr_time,air_time,everything())
head(data11)
```

## mutate()

```{r, eval=F}
flights_sml <- select(flights, year:day,
                      starts_with("dep"),
                      starts_with("arr"),
                      distance,air_time)
head(flights_sml)
```

```{r, eval=F}
mutate_flights_sml <- mutate(flights_sml,
                             gain=arr_delay-dep_delay,
                             speed=distance/air_time*60)
head(select(mutate_flights_sml,gain,speed,everything()))
```

```{r, eval=F}
transmute_flights_sml <- transmute(flights_sml,
                             gain=arr_delay-dep_delay,
                             speed=distance/air_time*60)
head(select(transmute_flights_sml,gain,speed,everything()))
```

```{r, eval=F}
flights1 = transmute(flights,
                     dep_time,
                     hour=dep_time%/%100,
                     minute=dep_time%%100)
head(flights1,3)
```

```{r, eval=F}
flights2 = transmute(flights1,
                     dep_time,
                     hour,
                     minute,
                     hrs_since_midnight=hour+minute/60)
head(flights2,3)
```

```{r, eval=F}
flights3=select(flights,distance)
ggplot(flights3) + geom_density(aes(x=distance))
```


```{r, eval=F}
flights4=transmute(flights,logdist=log(distance))
ggplot(flights4) + geom_density(aes(x=logdist))
```

```{r, eval=F}
flights5=transmute(flights,
                   dep_delay,
                   lag1_dep_delay=lag(dep_delay)
                   )
head(flights5, 5)
```

```{r, eval=F}
flights6=transmute(filter(flights,origin=="LGA",dest=="CLE",carrier=="UA"),
                   dep_delay,
                   rollsum_dep_delay=cumsum(dep_delay))
head(flights6,5)
```

```{r, eval=F}
flights7=arrange(transmute(filter(flights,origin=="LGA",dest=="CLE",carrier=="UA"),
                   air=air_time,
                   rank_air=min_rank(air_time),
                   percentile=percent_rank(air_time),
                   ecdf_air=cume_dist(air_time),
                   airtile5=ntile(air,5)),
                   air
                   )
head(flights7,5)
```

